config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options protocol: :https, host: 'kkubby.com'
  else
    default_url_options protocol: :http, host: 'localhost:3000'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new', as: 'login'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create', as: 'process_login'
  get 'search', to: 'product_search#index', as: 'product_search'
  put 'update_product_order', to: 'product_order#update', as: 'update_product_order'
  scope path: '@:username', as: 'user' do
    resources :shelves do
      resources :products, controller: 'shelf_products'
    end
    get :profile, to: 'profile#edit'
    patch :profile, to: 'profile#update'
  end
  get '/@:username', to: 'home#show', as: 'user_home'
  get 'signup', to: 'users#new'
  get 'user_search', to: 'user_search#index', as: 'user_search'
  get 'about', to: 'about#index'
  resources :users, only: :create
  resources :custom_uploads, only: [:index, :new, :create]
  root 'home#index'
end

app/controllers/product_search_controller.rb
class ProductSearchController < ApplicationController
  before_action :authenticate_user
  before_action :user_from_params

  def index
    @shelf = current_user.shelves.find(params[:shelf_id])
    @pagy, @products = pagy(load_products, items: 20)
  end

  private

  def load_products
    if params[:query].present?
      # Have to manually join catalogs cause association was causing extra queries on save (for some unknown reason)
      Product.joins('JOIN catalogs ON catalogs.id = products.catalog_id').where("catalogs.name ilike :q OR search_tokens @@ plainto_tsquery(:q)", q: params[:query].strip).order(:name).includes(:image_attachment => :blob)
    else
      Product.where('1=0')
    end
  end
end

app/views/product_search/index.html.erb
<div class="page-content">
  <% if current_user.custom_uploads? %>
    <div><p style="margin:0"><%= link_to "Upload your own product", new_custom_upload_path(shelf_id: @shelf.id, name: params[:query]), class: "btn wide", style: "text-shadow:none;font-weight:normal;padding-left:0;padding-right:0" %></p></div>
  <% end %>
  <p>Search for a product to add to your <strong><%= @shelf.name %></strong> shelf. You can search by catalog, name, brand, or product type.</p>
  <%= form_tag product_search_path(shelf_id: @shelf.id), method: 'get' do %>
    <%= hidden_field_tag :shelf_id, @shelf.id %>
    <div class="form-content">
      <%= text_field_tag :query, params[:query], class: 'text-input' %>
      <%= submit_tag 'Search', name: "", class: "btn wide" %>
    </div>
  <% end %>
  <% if @products.present? %>
    <% if @products.size < 20 && @pagy.pages == 1 %>
      <p>Found <%= @products.size %> products</p>
    <% else %>
      <p>Showing <%= @products.size %> out of <%= @pagy.count %> products</p>
      <%== pagy_nav(@pagy) %>
    <% end %>
    <table class="product-list">
      <tr>
        <th style="width: 160px"></th>
        <th></th>
      </tr>
      <% @products.each do |product| %>
        <tr>
          <td><%= link_to product_search_thumbnail(product), user_shelf_products_path(current_user, @shelf, id: product, query: params[:query]), method: 'post', remote: true, class: 'user-select-product' %></td>
          <td>
            <div class="box">
              <%= link_to user_shelf_products_path(current_user, @shelf, id: product, query: params[:query]), method: 'post', remote: true, class: 'user-select-product' do %>
                <p><strong><%= product.brand %></strong></p>
                <%= product.name %>
                <p class="small"><%= product.product_type %></p>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
    <%== pagy_nav(@pagy) %>
  <% elsif params[:query].present? %>
    <p>Nothing found. <span class="suggested-product"><%= suggested_product(params[:query]) %></span></p>
  <% end %>
</div>

<script type="text/javascript">
  document.getElementById('query').focus();
  document.getElementById('query').select();
</script>