config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options protocol: :https, host: 'kkubby.com'
  else
    default_url_options protocol: :http, host: 'localhost:3000'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new', as: 'login'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create', as: 'process_login'
  get 'search', to: 'product_search#index', as: 'product_search'
  put 'update_product_order', to: 'product_order#update', as: 'update_product_order'
  scope path: '@:username', as: 'user' do
    resources :shelves do
      resources :products, controller: 'shelf_products'
    end
    get :profile, to: 'profile#edit'
    patch :profile, to: 'profile#update'
  end
  get '/@:username', to: 'home#show', as: 'user_home'
  get 'signup', to: 'users#new'
  get 'user_search', to: 'user_search#index', as: 'user_search'
  get 'about', to: 'about#index'
  resources :users, only: :create
  resources :custom_uploads, only: [:index, :new, :create]
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :back_to
  attr_accessor :current_password
  has_secure_password
  has_many :shelves, dependent: :destroy
  before_create -> { generate_token(:auth_token) }
  validates :email, format: { with: EMAIL_PATTERN, allow_blank: true }
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: /\A\w+\z/ }
  before_validation :squeeze_username
  after_create ->(user) { Shelf.create_defaults(user) }

  def squeeze_username
    self.username &&= username.gsub(/\s+/, '').downcase
  end

  def display_username
    username.strip.humanize
  end

  def display_name
    name.presence || display_username
  end

  def to_param
    username
  end

  def share_link
    "kkubby.com/@#{username}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_title

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :username, :password))
    if @user.save
      sign_in_user(@user)
      redirect_to user_home_path(username: @user.username), notice: "Welcome, #{@user.username.capitalize}"
    else
      error_response(@user)
      render :new
    end
  end

  private

  def set_title
    @title = 'Kkubby - Signup'
  end
end

app/views/users/_user.html.erb
<div class="page-content profile-content">
  <div class="top-tab"><div class="top-tab-line"></div><div class="top-tab-line"></div></div>
  <div class="form-content">
    <%= form_for current_user, url: user_profile_path(current_user), remote: true do |f| %>
      <p>
        <%= f.label :name, 'Display name (public)' %>
        <%= f.text_field :name %>
      </p>
        <%= f.label :share_link, 'Share Link (public)' %>
        <%= content_tag(:div, current_user.share_link, class: 'like-input')  %>
      <p style="padding-top: 25px;">
        <%= f.submit 'Save Profile', class: 'btn wide', data: { disable_with: 'Save Profile' } %>
      </p>
      <div class="divider"></div>
      <p>
        <%= link_to 'Home', user_home_path(current_user), class: 'btn wide' %>
      </p>
      <p>
        <%= link_to 'User Search', user_search_path, class: 'btn wide' %>
      </p>
      <p>
        <%= link_to 'Logout', logout_path, class: 'btn wide' %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-content">
  <h3 class="page-header">Welcome to Kkubby</h3>
  <h4 class="page-header">Create a new account</h4>
  <div class="login-form form-content">
    <%= form_for(@user) do |f| %>
      <div>
        <%= f.label(:username, 'Pick a username (letters and numbers only)', class: 'medium-major') %>
        <div>
          <%= f.text_field(:username, tabindex: 1) %>
        </div>
      </div>
      <div>
        <%= f.label(:password, class: 'medium-major') %>
        <div>
          <%= f.password_field(:password, tabindex: 2) %>
        </div>
      </div>
      <div>
        <%= f.label(:email, 'Email (optional)', class: 'medium-major') %>
        <div>
          <%= f.email_field(:email, tabindex: 3) %>
        </div>
      </div>
      <div>
        <%= f.submit('Signup', class: 'btn wide', name: '', tabindex: 4) %>
      </div>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  document.getElementById('user_username').focus();
</script>