config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options protocol: :https, host: 'kkubby.com'
  else
    default_url_options protocol: :http, host: 'localhost:3000'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new', as: 'login'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create', as: 'process_login'
  get 'search', to: 'product_search#index', as: 'product_search'
  put 'update_product_order', to: 'product_order#update', as: 'update_product_order'
  scope path: '@:username', as: 'user' do
    resources :shelves do
      resources :products, controller: 'shelf_products'
    end
    get :profile, to: 'profile#edit'
    patch :profile, to: 'profile#update'
  end
  get '/@:username', to: 'home#show', as: 'user_home'
  get 'signup', to: 'users#new'
  get 'user_search', to: 'user_search#index', as: 'user_search'
  get 'about', to: 'about#index'
  resources :users, only: :create
  resources :custom_uploads, only: [:index, :new, :create]
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :user_from_params, only: :show

  def index
    if current_user
      redirect_to user_home_path(current_user)
    else
      @title = "Welcome to Kkubby"
      render "about/index"
    end
  end

  def show
    @shelves = cache @user do
      @user.shelves.includes(:shelf_products => { :product => { :image_attachment => :blob } }).references(:shelf_products).order('shelves.order_index').to_a
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def suggested_product(query)
    result = Product.spellcheck(query)
    if result
      content_tag(:span, "Did you mean? ") + link_to(result, product_search_path(shelf_id: @shelf.id, query: result), class: 'bold-link')
    elsif query.ends_with?("s")
      content_tag(:span, "Maybe try? ") + link_to(query.singularize, product_search_path(shelf_id: @shelf.id, query: query.singularize), class: 'bold-link')
    else
      content_tag(:span, "You could Google ") + link_to(query, "https://google.com/?q=#{query}", target: '_blank', class: 'bold-link')
    end
  end

  # @param [Product] product
  def product_thumbnail(product, wishlist: nil)
    css = "product-img"
    css += " wishlist" if wishlist
    product_image(product, mobile_device? ? 125 : 250, css)
  end

  # @param [Product] product
  def product_search_thumbnail(product)
    product_image(product, mobile_device? ? 175 : 250, "product-img")
  end

  def product_enlarged(product)
    product_image(product, mobile_device? ? 275 : 500, 'original-product-img fl')
  end

  def mobile_device?
    if request.env["HTTP_USER_AGENT"]
      request.env["HTTP_USER_AGENT"].match? /Mobile|Android/
    else
      false
    end
  end

  # @param [Product] product
  # @param [Integer] image_height
  # @param [String] css - classes to add to the image tag
  def product_image(product, image_height, css = nil)
    image_tag(product.stored_image(image_height),
              height: image_height, title: product.name, class: css, id: product.name.parameterize)
  end
end

app/views/home/_readonly_user_shelves.html.erb
<%= cache [@user, mobile_device?] do %>
  <table class="shelves">
    <% @shelves.each do |shelf| %>
      <tr>
        <td class="box shade">
          <%= content_tag :div, class: "shelf-name", id: shelf.name.parameterize do %>
            <span><%= shelf.name %></span>
          <% end %>
          <%= content_tag(:ul, class: "products", id: shelf.id) do %>
            <% shelf.shelf_products.sort_by(&:order_index).each do |sp| %>
              <%= content_tag(:li, id: sp.id, data: { href: user_shelf_product_path(@user, shelf, sp.product) }) do %>
                <%= product_thumbnail(sp.product, wishlist: sp.wishlist?) %>
              <% end %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/home/_user_shelves.html.erb
<%= cache [@user, mobile_device?] do %>
  <table class="shelves">
    <% @shelves.each do |shelf| %>
      <tr>
        <td class="box shade">
          <%= content_tag :div, class: "shelf-name", id: shelf.name.parameterize do %>
            <span class="editable-shelf-name"><%= shelf.name %></span>
            <%= form_for([@user, shelf]) { |f| f.text_field :name_with_index } %>
          <% end %>
          <%= content_tag(:ul, class: "products", id: shelf.id) do %>
            <% shelf.shelf_products.sort_by(&:order_index).each do |sp| %>
              <%= content_tag(:li, id: sp.id, data: { href: user_shelf_product_path(@user, shelf, sp.product) }) do %>
                <%= product_thumbnail(sp.product, wishlist: sp.wishlist?) %>
              <% end %>
            <% end %>
          <% end %>
          <%= link_to "+", product_search_path(shelf_id: shelf.id, query: shelf.name), class: 'add-product btn round' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td class="add-new-shelf">
        <div class="add-new-shelf-text"><p><a href="javascript:;" class="bold-link">+Add New Shelf</a></p></div>
        <div class="add-new-shelf-form form-content" style="display:none;">
          <%= form_for [@user, Shelf.new] do |f| %>
            <%= f.text_field :name, placeholder: "Enter a name", id: 'new_shelf_name' %>
            <%= f.submit "Create Shelf", name: "", class: "btn wide" %>
          <% end %>
        </div>
      </td>
    </tr>
  </table>
<% end %>

app/views/home/index.html.erb
<div class="page-content">
  <h3>Welcome!</h3>
  <p>KKubby is a virtual beauty cabinet that allows you to visually organize your skincare routine and share with
    others.</p>
  <h3>Your Skincare Routine</h3>
  <p>
    Organize your current products on our preset shelves (or customize them).
    Save products to your shelf, add notes, or mark as a wishlist item.
    Easily share your routine with friends using your Kkubby link.
  </p>
  <h3><%= Shelf::DEFAULTS.size %>-Step Routine</h3>
  <p>
    We start you off with <%= Shelf::DEFAULTS.size %> shelves, each representing a step in your routine:
  </p>
  <ol>
    <% Shelf::DEFAULTS.each do |name| %>
      <%= content_tag(:li, name) %>
    <% end %>
  </ol>
  <p>Steps can be added, renamed, and rearranged to fit your routine.</p>
  <h3>Share with Friends</h3>
  <p>Kkubbies are public by default, and accessible via your own URL, making it easy to share your routine with
    friends!</p>
  <h3>Create an Account</h3>
  <p>It's free to try it out. <%= link_to 'Create an account', signup_path %> to get started.</p>
  <p><%= link_to "Login", login_path %> if you already have an account.</p>
</div>

app/views/home/show.html.erb
<% if @shelves.present? %>
  <% if can_edit? %>
    <%= render partial: 'user_shelves', cached: true %>
  <% else %>
    <%= render partial: 'readonly_user_shelves', cached: true %>
  <% end %>
<% else %>
  <p>No shelves created yet. Want to add one now?</p>
<% end %>