config/routes.rb
Rails.application.routes.draw do
  if Rails.env.production?
    default_url_options protocol: :https, host: 'kkubby.com'
  else
    default_url_options protocol: :http, host: 'localhost:3000'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'login', to: 'sessions#new', as: 'login'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'login', to: 'sessions#create', as: 'process_login'
  get 'search', to: 'product_search#index', as: 'product_search'
  put 'update_product_order', to: 'product_order#update', as: 'update_product_order'
  scope path: '@:username', as: 'user' do
    resources :shelves do
      resources :products, controller: 'shelf_products'
    end
    get :profile, to: 'profile#edit'
    patch :profile, to: 'profile#update'
  end
  get '/@:username', to: 'home#show', as: 'user_home'
  get 'signup', to: 'users#new'
  get 'user_search', to: 'user_search#index', as: 'user_search'
  get 'about', to: 'about#index'
  resources :users, only: :create
  resources :custom_uploads, only: [:index, :new, :create]
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="robots" content="index,follow">
  <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1">
  <meta name="turbolinks-cache-control" content="no-cache">
  <meta name="theme-color" content="#8C494E">
  <title><%= @title || 'Kkubby' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <% if Rails.env.production? %>
    <script src="//d2wy8f7a9ursnm.cloudfront.net/v7/bugsnag.min.js"></script>
    <script>Bugsnag.start({ apiKey: '927d8f5d3bbd63da38cc55b5bd2d85e2' })</script>
  <% end %>
  <% if @product %>
    <meta property="og:title" content="<%= @product.full_name %>" />
    <meta property="og:image" content="<%= polymorphic_url(@product.stored_image) %>" />
  <% end %>
</head>
<body class="<%= 'user-signed-in' if current_user %>">
<div class="top-bar">
  <div class="top-bar-content">
    <%= link_to home_path, class: 'bold-link' do %>
      <div class="fl">
        <% if @user&.persisted? %>
          <div class="top-bar-username"><%= @user.display_name %>'s</div>
        <% end %>
        <h1>Kkubby</h1>
      </div>
    <% end %>
    <div class="hamburger">
      <%= link_to image_tag('white-panda.svg', height: 50, width: 50), login_path %>
    </div>
  </div>
  <div class="clear"></div>
</div>
<%= flash_message_helper %>
<div class="page-body" id="page-body"><%= yield %></div>
<div class="footer">
  <div class="divider"></div>
  <p>Kkubby Inc &copy; 2022</p>
  <p><%= link_to "About Us", about_path, class: 'bold-link' %> | <%= link_to 'Signup', signup_path, class: 'bold-link' %></p>
  <p>Contact us <%= link_to "@mykkubby", "https://instagram.com/mykkubby", target: '_blank', class: 'bold-link' %></p>
  <p class="code-text medium">v<%= Rails.application.config.version %></p>
</div>
<% if current_user %>
  <div class="profile-modal"><div id="profile" class="profile"><%= render current_user %></div></div>
<% end %>
</body>
</html>